title: Page

options: 
  template: true  
  status: true

fields:
  title:
    label: Заголовок
    type:  text

  text:
    label: Текст
    type:  textarea

  meta:
    label: Meta
    type: headline

  meta_title:
    label: Заголовок (meta-title)
    type: text

  meta_keywords:
    label: Ключевые слова (meta-keywords)
    type: textarea

  meta_description:
    label: Описание (meta-description)
    type: textarea
