title: Service

files: true

options: 
  template: true  
  status: true  
  
fields:
  title:
    label: Заголовок
    type: title
    
  intro:
    label: Вводный текст
    type: text
    
  text:
    label: Основной текст
    type: textarea

  table:
    label: Таблица
    type: textarea

  meta:
    label: Meta
    type: headline

  meta_title:
    label: Заголовок (meta-title)
    type: text

  meta_keywords:
    label: Ключевые слова (meta-keywords)
    type: textarea

  meta_description:
    label: Описание (meta-description)
    type: textarea
