title: Services

files: true

options: 
  template: true  
  status: true

pages:
  template: service
  
fields:
  title:
    label: Title
    type: title
    
  intro:
    label: Intro
    type: textarea
    
  text:
    label: Text
    type: textarea
