title: Services

files: true

options: 
  template: true  
  status: true

pages:
  template: service
  
fields:
  title:
    label: Заголовок
    type: title
    
  intro:
    label: Вводный текст
    type: textarea
    
  text:
    label: Основной текст
    type: textarea

  meta:
    label: Meta
    type: headline

  meta_title:
    label: Заголовок (meta-title)
    type: text

  meta_keywords:
    label: Ключевые слова (meta-keywords)
    type: textarea

  meta_description:
    label: Описание (meta-description)
    type: textarea
