title: Service

files: true

options: 
  template: true  
  status: true  
  
fields:
  title:
    label: Title
    type: title
    
  intro:
    label: Intro
    type: text
    
  text:
    label: Text
    type: textarea

  table:
    label: Table
    type: textarea

  guarantees:
    label: Guarantees
    type: textarea
