title: Site

files: true
  sortable: true
  fields:
    caption:
      label: Описание
      type: text

fields:
  title:
    label: Заголовок
    type:  text

  author:
    label: Автор
    type:  text
    
  copyright:
    label: Copyright
    type:  textarea

  warranties:
    label: Гарантии для страниц с услугами 
    type: headline
    numbered: true

  warranty:
    label: Гарантия
    type: textarea

  meta:
    label: Meta
    type: headline

  meta_title:
    label: Заголовок (meta-title)
    type: text

  meta_keywords:
    label: Ключевые слова (meta-keywords)
    type: textarea

  meta_description:
    label: Описание (meta-description)
    type: textarea